image: Ubuntu1804 # образ для сборки

stack: node 16 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  - yarn install # команда установки зависимостей

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build # команда сборки



deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name Elshina25
  - git config --global user.email salnaya92@gmail.com
  - echo "https://$GITHUB_TOKEN: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" > "$HOME/.git-credentials"
  # - npx push-dir --dir=build --branch=gh-pages --force --verbose